#pragma once

enum Errors {
	INPUT_NO_CRITICAL_ERROR = 10,
	INPUT_PREPARE_ERROR = 100,
	INPUT_PREPARE_CODEC = 101,
	INPUT_PREPARE_DECODER = 102,
	INPUT_DECODE_ERROR = 103,
	INPUT_DECODE_TRANSFER = 104,
	OUTPUT_NON_CRITICAL_ERROR = 200,
	OUTPUT_PREPARE_ERROR = 220,
	OUTPUT_PREPARE_CODEC = 221,
	OUTPUT_PREPARE_STREAM = 222,
	OUTPUT_PREPARE_CODEC_CONTEXT = 223,
	OUTPUT_PREPARE_ALLOC_FRAME = 224,
	OUTPUT_PREPARE_ALLOC_HW_CONTEXT = 225,
	OUTPUT_PREPARE_COPY_PARAMS = 226,
	OUTPUT_PREPARE_OPEN_CODEC = 226,
	OUTPUT_PREPARE_OPEN_BSF_FILTER = 227,
	OUTPUT_PREPARE_OPEN_FILTER = 228,
	OUTPUT_PREPARE_INPUT_OPT = 229,
	OUTPUT_PREPARE_OPEN_FILE = 230,
	OUTPUT_PREPARE_BSF_FILTER = 231,
	OUTPUT_WRONG_FRAMERATE = 232,

	OUTPUT_TRANSFER_DATA = 231,
	OUTPUT_ENCODER = 232,
	OUTPUT_FILTER = 233,
	OUTPUT_BSF_FILTER = 233,
	OUTPUT_FRAME = 234,

	MANAGER_ERROR = 300

};
