package com.checkmate.android.viewmodels;

public enum EventType {

    CAM_HELP_RELEASE_LIVE,
    IC_STREAM_ACTIVE_LIVE,
    IC_STREAM_LIVE,
    SPEE_TEXT_LIVE,
    VU_METER_VISIBLE,
    ASPECT_RATIO_LIVE,
    SET_NETWORK_TEXT_LIVE,
    SET_WIFI_INFORMATION_LIVE,
    RELEASE_CAMERA_LIVE,
    HANDEL_STREAM_VIEW_LIVE,
    STREAM_USB_LIVE,
    USB_RECORD_LIVE,
    NETWORK_UPDATE_LIVE,
    WIFI_STREAMING_STARTED_LIVE,
    STOP_WIFI_STREAMING_STARTED_LIVE,
    HANDEL_CAM_STREAM_VIEW_LIVE,
    NETWORK_CHANGED_LIVE,
    HANDLE_CAMERA_VIEW_LIVE,
    ON_CAST_STREAM,
    INIT_CAM_SPINNER_LIVE,
    NOTIFY_CAM_SPINNER_LIVE,
    INIT_FUN_LIVE_FRAG,//initialize()
    INIT_FUN_SETTING,//initialize()
    STORAGE_PATH_SETTING,//initialize()
    STORAGE_PATH_PLAY_BACK,//initialize()
    INIT_FUN_PLAY_BACK,//initialize()
    UPDATE_DEVICE_STREAMING,//updateDeviceStreaming()
    UPDATE_DEVICE_STREAMING_DOUBLE_VAL,//updateDeviceStreaming()
}
